[package]
name = "log_aggregate"
version = "0.1.0"
authors = ["Antonin P.A. <aperrotaudet@netwo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "log_aggregate"
path = "src/main.rs"

[dependencies]
